ximion/appstream

qt/CMakeLists.txt

After discussing with Ximion it, it looks like nobody is using
Appstream-Qt4, so it's fair to just use by default the most common
one.
At some point it will make sense to make it Qt5 only, to take
advantage of Qt5 features. This is just a first step.

Make Qt5 default

---

po/POTFILES.in

Fixes errors on https://l10n.gnome.org/module/appstream/

Updated POTFILES.in

---

src/as-component.c

Three annotations were missing.

Add missing annotations

---

CMakeLists.txt

eaf7229d57ccb77ca29efcfa2bf719ba8fbab568 suggests that it was bumped to
3.2 for CMAKE_CXX_STANDARD, this feature was however introduced in 3.1.
lower the cmake requirement from 3.2 to 3.1 to align with the actual
requirements
tested on 3.1.1

lower cmake requirement to 3.1.0

---

qt/component.cpp
qt/database.cpp
qt/provides.cpp
qt/test/qtdbreadtest.cpp
qt/test/testpaths.h.in

Don't rely on QString(const char*)
Prefer splitting with char than with a string.
Leverage Q_GLOBAL_STATIC.

Improve Qt5 usage

---

qt/database.cpp

Don't forget about screenshots.
Allocate before populating for better performance (reduced allocations).

Polishing of the Qt interface

---

src/as-cache-builder.c

It's possible that a suite/arch will have no packages with AppStream; we
shouldn't crash in that case.
g_strstr_len will return NULL if the string we're searching for ("---")
is not found - this will be the case if there are only the headers and
no further documents. In that case we should read to the end of the
file.
While doing this, I made this bit (IMO) easier to read by renaming some variables and adding comments, hope you like that.

as-cache-builder: Cope with no YAML documents

---

src/as-metadata.c

Fixes #35, Refresh hangs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ximion/appstream/36)

Ensure decompressed metadata is null-terminated

---

src/as-component.c

Change documentation on method as_component_get_id from:
Set the unique identifier for this component.
To:
Get the unique identifier for this component.

Fix code documentation for as_component_get_id

---

src/as-xmldata.c

Fix two method documentations on xmldata.c that started with as_component.

Fix some xmldata methods documentation

---

qt/component.h
qt/image.h
qt/provides.h

See https://woboq.com/blog/q_enum.html

Properly expose enums for introspection

---

qt/component.cpp
qt/component.h

This way we can return it as a block so that the client can actually
introspect which icons are available.
The code I'm referring to looks like this:
```
{
QIcon ret;
const auto icons = m_appdata.iconUrls();
if (icons.isEmpty())
return m_appdata.name();
else {
for (auto it = icons.constBegin(), itEnd = icons.constEnd(); it!=itEnd; ++it) {
if (it->isLocalFile())
ret.addFile(it->toLocalFile(), it.key());
}
}
return ret;
}
```

Different approach for storing the icon size and url relation

---

docs/sources/distrospec/asxml.xml
docs/sources/metaspecs/addondata.xml
docs/sources/metaspecs/codecdata.xml
docs/sources/metaspecs/component.xml
docs/sources/metaspecs/desktopappdata.xml
docs/sources/metaspecs/firmwaredata.xml
docs/sources/metaspecs/fontdata.xml
docs/sources/metaspecs/inputmethoddata.xml

Various minor typo and formatting fixes for parts of the specifications (I haven’t done everything thoroughly).

Specification proofreading fixes

---

qt/CMakeLists.txt
qt/component.cpp
qt/component.h
qt/database.cpp
qt/release.cpp
qt/release.h

This way we can access release information when using libappstreamqt

Implement Appstream::Release for the Qt interface

---

src/as-cache-file.c

Fixes #70.
On 1084 the `checksums` dictionary is retrieved, but then we look at `var`, which is something else entirely.

as-cache-file: Iterate the right dictionary when looking at checksums

---

src/as-distro-extras.c

Not sure why these end up here, but we should deal with it either way.
Fixes #72

Deal with broken apt symlinks

---

src/as-pool.c

Although the comment header in as_pool_search claims that the results are returned unordered, they are specifically ordered from lowest to highest match score. If search results are going to be sorted, I believe it makes more sense for higher scores to be at the top of the list.
Fixes #77.

Sort search results by highest to lowest match scores

---

tools/appstream-cli.c

I noticed the "--help" text was no longer accurate in recent versions of appstream. I replaced the "refresh-index" text with the "refresh" command. This could also or alternatively show "refresh-cache" if preferred, but it seems the pattern is to show the basic command in the "help" text and alternatives in the man page.

Replace refresh-index with refresh in help text

---

qt/database.cpp

without this an unopened database goes boom because the pointer points to garbage

Fix database dtor crash

---

src/CMakeLists.txt

In Mageia, the libstemmer headers are in `/usr/include/libstemmer`, while in Fedora and other distributions, they are in `/usr/include`.
We will now support both paths.

Add path search to find libstemmer headers

---

qt/pool.cpp
qt/pool.h

As discussed in the issue #97, there's some systems where appstream is
reporting that it doesn't load properly but the users on the platform
don't have information on how to fix it.
With this warning, they will at least have a chance to know.

Provide an error message as warning output

---

qt/CMakeLists.txt
qt/bundle.cpp
qt/category.cpp
qt/category.h
qt/chelpers.h
qt/component.cpp
qt/component.h
qt/contentrating.cpp
qt/contentrating.h
qt/icon.cpp
qt/icon.h
qt/image.cpp
qt/image.h
qt/launchable.cpp
qt/launchable.h
qt/provided.cpp
qt/provided.h
qt/release.cpp
qt/release.h
qt/screenshot.cpp
qt/screenshot.h
qt/suggested.cpp
qt/suggested.h
qt/translation.cpp
qt/translation.h

Note: only two of them should be missing (launchables and languages), because
we don't have wrappers for them yet

Add missing getters/setters for most of the properties in AS::Component

---

docs/sources/quickstart/Quickstart.xml
docs/sources/quickstart/addons.xml
docs/sources/quickstart/desktop-apps.xml
docs/sources/quickstart/packaging.xml

Debian and Ubuntu have a usability problem with the GNOME Software app.
1. Removing GNOME Books removes GNOME Documents since they are both included in the same package.
2. Enabling one addon for Eye of GNOME installs all of eog's addons and disabling one addon removes all of eog's addons. (This affects a few other apps too.)
This pull request helps to fix this problem by standardizing a few best practices for distros.
The commented line looks like a typo introduced in https://github.com/ximion/appstream/commit/40431c63e7cd13f1d18f69c69e29cd0fd3f20525 so I fixed that too.

doc: Add guidelines for distributors

---

qt/CMakeLists.txt
qt/metadata.cpp
qt/metadata.h

Same PR as https://github.com/ximion/appstream/pull/118, I just wasn't able to squash all the commits into one as there were some other commits among them.

Add AS::Metadata class used for parsing desktop and appstream metadata files

---

docs/sources/collection/xmldata.xml
docs/sources/metainfo/component.xml

Previously the doc was a bit ambiguous about the actual format employed
for licenses. The format expectation is the actual SPDX license expression
format as described in the SPDX specification.
Clearly state this and point to the specification URL for reference on the
format.
Additionally, while SPDX must be parsed as case-insensitive it's considered
best practice to use strict-casing in examples, so change to that.
Closes #122

trivial: adjust docs to clearly state that licenses are SPDX expressions

---

qt/pool.cpp

See backtrace:
https://bugs.kde.org/show_bug.cgi?id=382916
I fixed it in Discover, but it shouldn't be crashing anyway.

Don't crash when an error is found and no error string is passed

---

docs/sources/metainfo/component.xml

This is used by the upcoming Cockpit "Software Center": https://github.com/cockpit-project/cockpit/pull/7076

spec: New "cockpit-manifest" launchable type

---

docs/sources/collection/xmldata.xml
docs/sources/metainfo/component.xml

And not just in the collection metadata.  This way, components of type
"service" and any other other component can specify icons upstream in
a standardized way.

spec: Allow <icon> tags in generic components

---

qt/AppStreamQtConfig.cmake.in
qt/cmake/AppStreamQtConfig.cmake.in

Otherwise it only works if it's installed in /usr as a prefix (where it's
a default)

Export the AppStreamQt target

---

docs/sources/quickstart/translation.xml

Add enough information to the intltool section of the metadata quickstart to show how to get the appstream XML file translated.
This commit is not tested. I found straightforward building, (Travis) testing, and xml validation was not practical.

Add quickstart instructions for intltool

---

docs/sources/metainfo/component.xml

The logics behind this proposition is that in GIMP, we have development release. Someone is proposing us to add <releases> tag in our appdata. So far so good.
But he also wants <release> items for the development releases. And that's where I am wondering if that is really relevant information. Well this is definitely relevant for anyone installing such development versions. But for most people, these are releases they will never see (and barely know they exist), and that's normal (distributions are certainly not expected to distribute them). Therefore if such a release listing (is there any software making usage of this tag by the way? GNOME Software 3.26 at least doesn't seem to do anything from it) were to include development versions, this would confuse people.
This is why I am …

Propose a "type" property to <release/> tag.

---

src/as-distro-extras.c

It's either an issue here or with APT itself, on my system I had
/var/lib/apt/lists/packages.elementary.io_appcenter_dists_xenial_main_dep11_icons-64x64%25402.tar.gz
And of course, the hidpi wasn't available because of the arobase :)

apt: escape the icon scale factor as it is using the @ character

---

qt/component.cpp
qt/component.h

Fixes a crash when no deref/ref on = operator.
Makes it possible to leverage move semantics on components.

Implement missing constructors

---

src/as-component.c

If the component doesn't contain translated data for the given locale string, try the plain language string before falling back to C
Fixes #166

Check also plain language string in as_component_localized_get

---

data/its/metainfo.its

https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html allows to provide information about releases.
This PR aims at allowing xgettext to list them as translatable strings.

Allow release description translations

---

src/as-component.c
src/as-content-rating.c
src/as-icon.c
src/as-image.c
src/as-pool.c
src/as-release.c
src/as-screenshot.c
src/as-utils.c

Together, these were leaking megabytes at a time in the downstream program isenkramd every time I plugged in my mouse.

Fix memory leaks

---

src/as-pool.c
tests/test-pool.c

In as_pool_save_cache_file() and test_pool_read() we were calling
g_ptr_array_unref() without NULLing the autopointer. This results in
two unrefs for one ref which is bad.
This is breaking the testsuite with GLib 2.57.2 which now catches this and throws a critical.

Fix a couple of incorrect g_ptr_array_unrefs

---

src/as-pool.c

When as_pool_refine_data encounters bad components, this is reflected
in the return code, but there is no further information given what went
wrong. Give a short hint to the user, and refer to the debug output which
allows determining the cause.

Set error variable if there were some errors during refinement

---

src/as-pool.c

Currently, only a maximum of one addon is associated with a component.
As far as I understand it, a component should be able to have multiple addons. I.e. multiple components can all have an `extends` field that points to the same component.
In this PR, when looking at the extends field, make sure we add the current component to the addons section of the extended package if the current component isn't in the addons list already, rather than artificially limiting it to 1 addon per component.

Allow multiple addons per component

---

src/as-component.c

These types are not marked as nullable in the resulting GIR file and hence not marked nullable in any bindings downstream of that; for example, the Vala bindings.
Having these marked as nullable would allow more robust Vala code to be generated when these methods are used.
This only touches Component for now in case there's some reasoning behind why these haven't been marked `nullable`, but I'm happy to submit a PR to cover off the rest if this is wanted.

component: Mark relevant return types as nullable

---

src/as-pool.c

See 8213577d1ee72385a27c79a546564a52bcfba93a

as-pool: Fix g-i for get_components_*() while GPtrArray owns its elements

---

docs/sources/metainfo/component.xml

This is a proposition for allowing `<url>` inside the `<release>` tag as discussed in the pull request #158.
We do very nice news post on gimp.org now, with a lot of screenshots, explanations and much more, and a link to these would be very good in a release listing for people who want to know more.
And for release notes too. :-)

Release url

---

docs/sources/metainfo/localization.xml

Reference Collection's 'languages' tag from the localization page, so upstream don't get confused into generating language packs metadata to reference bundled gettext .mo files. Both pages define a 'languages' tag.

doc: help distinguish the 2 'languages' tags

---

docs/sources/metainfo/component.xml

Cockpit doesn't support those, but we have a request for it. Let's clarify the spec.
If nested lists are in fact supported, that's just fine as well, of course, but let's clarify that also.

docs: Explicitly rule out nested lists

---

data/its/metainfo.its

Some package does not wish to extract the component name
as translatable since it's the branding name and add the
translatable option.
https://github.com/ximion/appstream/issues/229

its: Add translatable option in metainfo.its

---

README.md
docs/meson.build
meson_options.txt

--install-docs=false can be used to disable installation of documentation,
which right now can't be disabled as it was possible with cmake.

Add install-docs meson build option.

---

src/as-provided.c

As per 
https://en.wikipedia.org/wiki/D-Bus
and
https://www.iana.org/assignments/media-types/media-types.xhtml

Spelling: DBus→D-Bus, MIME types → Media types

---

src/as-cache.c

Otherwise we get a bunch of addons whenever we search for the
application in question.
See https://bugs.kde.org/show_bug.cgi?id=407588
After:
```
Identifier: org.kde.kdevelop.desktop [desktop-application]
Name: KDevelop
Summary: Featureful, plugin-extensible IDE for C/C++ and other programming languages
Package: kdevelop
Homepage: https://kdevelop.org
Icon: kdevelop_kdevelop.png
---
Identifier: org.kde.kdev-python [addon]
Name: KDevelop Python Support
Summary: Python language support for KDevelop
Package: kdevelop-python
Homepage: https://kdevelop.org
Icon: kdevelop-python_kdevelop.png
---
Identifier: org.kde.kdev-php [addon]
Name: KDevelop PHP Support
Summary: PHP language support for KDevelop
Package: kdevelop-php
Homepage: https://kdevelop.org
Icon: kdevelop-php_kdevelop.png
``` …

Sort addons less prominently than applications

---

docs/sources/metainfo/component.xml
src/as-relation.c
src/as-relation.h

Hi!
These are the proposed spec changes and an initial implementation (missing tests and specific validator checks at the moment) of **user input controls**.
These can be used to indicate which methods of control by a user an application supports. This permits filtering applications that are mobile-ready to a limiting degree by checking whether they support touch input. Also, games could mark that they do support game controllers, as initially requested in https://github.com/ximion/appstream/issues/55. Applications that do have a CLI or support voice/vision as methods of user control can also be pointed out to the user.
This PR implements the addition proposed as https://lists.freedesktop.org/archives/appstream/2020-February/000339.html which also contains additional information about its …

User input control information in AppStream

---

src/as-cache.c

I've been looking into some of the searching/sorting logic and I'm not 100% sure on this change due to not being overly familiar with the code and not having worked the logic all the way back yet, but given that
```
ENTRY_LEN = sizeof(AsTokenType) + AS_CACHE_CHECKSUM_LEN * sizeof(guint8);
```
It looks like there is one `AsTokenType` per result, yet it seems the pointer arithmetic for updating `sort_score` doesn't take the array index into account.

as-cache: Use correct FTS value per result

---

qt/provided.h

It was never added to the Qt interface

qt: add missing Provided::KindId enum

---

src/as-cache.c

Currently the FD referring to the appstreacm-cache-FOO.mdb is leaked into
child processes. The only way to fix is in a race-free way is by passing
O_CLOEXEC when opening it inside LMDB, but that's currently not done.

Set FD_CLOEXEC on the LMDB FD manually

---

docs/xml/metainfo-component.xml
src/as-relation-private.h
src/as-relation.c
src/as-relation.h
tests/test-xmldata.c
tests/test-yamldata.c

This change adds specification text to allow applications to require a minimum display width and/or height in order to be installed or run with recommended settings.
This change would address https://github.com/ximion/appstream/issues/285 
CC: @hughsie @apol @hadess @Exalm

WIP: Specify display_length requires/recommends item

---

src/as-metadata.c

I used to get:
```
** (process:12057): DEBUG: 05:26:52.319: No component found in desktop-entry file: SparkleShare.Autostart.desktop
(process:12057): GLib-CRITICAL **: 05:26:52.319: g_propagate_error: assertion 'src != NULL' failed
```
Possibly because the desktop file is broken, but it's good not to throw critical errors like that.

Do not propagate a null GError

---

meson.build
tools/ascli-actions-mdata.c

This makes the code a little more amenable to being built as a
subproject for projects like gnome-software, which use standard C.
See `man 7 feature_test_macros` for details of the vendor extension
macros.

build: Use c11 rather than gnu11 and define vendor extensions separately

---

docs/xml/metainfo-component.xml

As per discussion on #309, it should be `LicenseRef-proprietary`, rather
than `LicenseRef-Proprietary`.
Helps: #309

spec: Fix case of LicenseRef-proprietary in the spec

---

docs/xml/collection-iconcache.xml

docs: Fix a typo on the icon cache page

---

docs/xml/metainfo-component.xml

spec: Add a paragraph about which license to put in <project_license>

---

src/as-content-rating.c
src/as-content-rating.h

This is technically an API break, but since it was a violation of the
GObject naming conventions, it seems likely that nobody had encountered
it before (or relied on it), otherwise it would have been reported.

as-content-rating: Fix a typo in the type macro for AsContentRating

---

src/as-component.c
src/as-desktop-entry.c

We're failing to translate strings now, when the keywords ends with a
";" as they almost always do, e.g.:
Keywords=Drivers;Repositories;Repository;PPA;
because we strip the trailing semicolon off before translating, in order
to avoid having empty elements in the output.
Instead what we can do is process the list passed to
`as_component_set_keywords` and remove empties at that point. This
allows us to not modify the string retrieved from the desktop file, and
fixes finding translations.

component: Don't strip ";" from keywords before translating them

---

compose/asc-font.c
src/as-context.c
src/as-news-convert.c
src/as-spdx.c
src/as-utils-private.h
src/as-utils.c
src/as-utils.h
src/as-yaml.c
tests/test-misc.c
tools/ascli-utils.c

We have some locales which are dupes if we do this, for example ca_ES.UTF-8 and ca_ES.UTF-8@valencia. The latter of these should become ca_ES@valencia in the output. That is what `locale -a` shows.
Previously `as_locale_strip_encoding ()` modified the passed-in string in place. However, in the one place where don't `g_strdup ()` the string before passing to this function, it is the key in a `GHashTable`. We can't do this, and only get away with it because the hash table isn't touched after this call. Fix the function to instead return a newly allocated string, and drop the `g_strdup` calls from the other call sites.
Add a small test for this function too.
https://github.com/ximion/appstream-generator/issues/92

utils: Don't strip modifiers when stripping encoding

---

compose/asc-globals.c
compose/asc-image.c
tests/test-compose.c

There are two places we can beef up the checks for optipng
- When enabling its usage, make sure we found it first, and refuse to
enable if we didn't.
- In case `asc_compose_set_optipng_binary (NULL)` was called, check
before spawning that we have *a* path. It's a programmer error to
call `g_spawn_sync ()` with `NULL` in `argv[0]`, and the program
will crash in that case. Also treat `NULL` as disabling optipng when
passed to `asc_compose_set_optipng_binary`.
In case the binary is removed mid-run or an invalid binary is passed to
`asc_compose_set_optipng_binary`, the `g_spawn_sync` call itself will
fail and we'll report a proper GError. This is the best way to handle
it, as we avoid TOCTTOU races that way.

compose: Check optipng is there before we use it

---

qt/pool.h

It's not the default but what we generally do. It allows us to call
parent class methods normally.

qt: Make Pool's parent class public

---

.github/workflows/build-test.yml
tests/ci/Dockerfile-fedora-latest
tests/ci/Dockerfile-fedora-rawhide
tests/ci/install-deps-rpm.sh
tests/ci/run-build.sh

As Fedora ships updated GNOME components often earlier than anyone else,
it makes sense to test this to ensure that this continues to work.

ci: Add Fedora to the CI environment

---

docs/xml/collection-xmldata.xml
docs/xml/metainfo-component.xml

As I understand it, these changes just document the existing semantics
and don’t change anything.

spec: Mention the already-supported scale attribute of <icon/>

---

compose/asc-utils-l10n.c
docs/xml/metainfo-component.xml
src/as-translation.c
src/as-translation.h
tests/samples/appdata.xml
tests/test-compose.c
tests/test-xmldata.c

This allows specifying the locale of the source translatable strings
in a component. The vast majority of the time, this is `en_US`, but
that’s not guaranteed. Add a `source-locale` attribute to allow changing
this default.
Helps: #345

spec: Add support for source locales

---

src/as-metadata.c

While working on the port of Flatpak to libappstream[1] I noticed that
we currently don't have proper error checking when loading an appstream
file with appstream-glib that turns out not to exist.[2] appstream-glib
was patched to return G_IO_ERROR_NOT_FOUND in that case[3] and
libappstream already does so in its corresponding API, but this patch
documents that so that if the implementation here is changed it will
hopefully still meet this requirement.
[1] https://github.com/flatpak/flatpak/pull/4426
[2] https://github.com/flatpak/flatpak/blob/284edffe89ecb78a19d01da065030d9f3bf31c76/app/flatpak-builtins-utils.c#L1169
[3] https://github.com/hughsie/appstream-glib/pull/268

metadata: Document file not found error code

---

contrib/vapi/AppStream-1.0-custom.vala

Using the previously unknown PoolFlag made it an API break.

contrib/vapi: Rename PoolFlag to PoolFlags to add the missing deprecated flags

---

src/as-component.c
src/as-file-monitor.c
src/as-pool.c
src/as-utils.c

Those version never existed and were replaced by 0.15.0

trivial: Change mentions of 0.14.7 and 0.14.8 to 0.15.0

---

docs/xml/collection-xmldata.xml

This property is inserted[1] into XML collection metadata by
appstream-generator, but is undocumented.
[1]https://github.com/ximion/appstream-generator/blob/master/src/asgen/engine.d#L318

docs: document media_baseurl property of components

---

src/as-validator-issue-tag.h
src/as-validator.c

`appstream-util` checks for missing timestamp property, so we can do the same.
What prompted me to check this, was having had a typo `data=...` instead of `date=...` which was caught by `appstream-util`, but not by `appstreamcli`.
An alternative solution could iterate the properties of the release tag and check for unknowns (if that is preferred).
I'm also not sure if the info severity is a good choice or if it should be bumped to warning

Check missing release props

---

qt/component.cpp

We need to invalidate the one we are moving, otherwise we get a 2x
unref.

qt: Fix crash when moving a Component

---

compose/asc-canvas.c

We should only scale the canvas in the legacy path, since the viewport
already takes care of scaling.
Also, while we're here:
- We should `cairo_save` before scaling, so that on error the
`cairo_restore` doesn't leave the canvas in the scaled state.
- The SVG size is only used in the legacy path.
- We don't inspect the error so no need to have `tmp_error`.
Fixes: https://github.com/ximion/appstream/issues/375

compose: Fix SVG scaling with librsvg 2.52

---

qt/component.cpp

While looking at the source, I saw that UrlTranslate is defined in Header as part of UrlKind but not set.
btw:
Is there any reason why it is named UrlTranslate and not UrlKindTranslate like the other?

Fix translate URL

---

docs/xml/metainfo-component.xml

Follow up from https://github.com/ximion/appstream/issues/187. See the commit messages for details:
* Fix some typos
* Suggest a strict format for hexadecimal colour values to make parsing and future extensions easier.

A couple of minor fixes to the branding spec

---

src/as-component-private.h
src/as-component.c

* trivial: Make as_component_create_token_cache static
It's no longer called from outside AsComponent, so it doesn't need to be
extern any more.
* AsComponent: Centralize GOnce guard to fix an assertion failure
The token cache only needs to be created once per AsComponent.
Previously, each of the two callers of as_component_create_token_cache()
guarded it with an atomic (GOnce) access to priv->token_cache_valid,
but the implementation had a redundant non-atomic guard. This resulted
in a GLib assertion failure on leaving the function, because the atomic
boolean flag indicating whether initialization has completed is not
meant to be set non-null until g_once_init_leave().
In particular, this resolves test failures in Flatpak 1.13.x
(which has been ported from libappstream-glib to …

AsComponent: Centralize GOnce guard to fix an assertion failure

---

qt/release.cpp

Otherwise we are creating a date in the seventies that is believed to be
true.
Addresses the discussion here:
https://invent.kde.org/plasma/discover/-/merge_requests/266#note_411067

qt: If the timestamp is 0, return a default QDateTime()

---

docs/xml/metainfo-component.xml
src/as-enums.c
src/as-enums.h
tests/test-xmldata.c
tests/test-yamldata.c

This PR adds vcs-browser and contribute as URL types as in #374. It was easier and cleaner to make a new PR than to update the old one.

Add vcs-browser and contribute URL type

---

data/org.freedesktop.appstream.cli.metainfo.xml
data/org.freedesktop.appstream.compose.metainfo.xml

This PR adds the new vcs-browser URL type to own metainfo files of appstream.

Add vcs-browser URL to metainfo.xml

---

src/as-validator-issue-tag.h
src/as-validator.c

Fixes #402. This fix is a simple if, which doesn't needed much experience in C, so I decried to do the fix myself. I checked for a Timestamp smaller than 3000, if someone has the idea to use the Year as timestamp. I guess no one wants to use 1970/1/1 as release date in the Appstream, so it wouldn't break anything.

Validate timestamp

---

src/as-relation.c

The current implementation returns AS_DISPLAY_LENGTH_KIND_SMALL when px is higher than 360 and AS_DISPLAY_LENGTH_KIND_XSMALL when px is 360 or lower. All other are not returned. This bug was found by LGTM.

Fix as_display_length_kind_from_px()

---

src/as-validator-issue-tag.h
src/as-validator.c

This checks, if the content of <memory> is a number

Add validation for <memory>

---

data/update-data.py

Use lxml to get the list of XDG categories from the DocBook file using
XPath queries; this simplifies the code a bit, and makes it more robust.
There is no change in the extracted data.

data: use lxml to get the XDG categories

---

docs/xml/metainfo-component.xml
src/as-relation.c
src/as-relation.h
tests/test-xmldata.c
tests/test-yamldata.c

This is a fixed up version of https://github.com/ximion/appstream/pull/421 that is ready to merge (due to @pwithnall being on vacation and there's no reason to leave this 99.9% completed feature out of the next release).
@cassidyjames @JakobDev Please have a look if you see any issues, otherwise I hope I can merge this in time for the release that will likely happen in the evening next Monday.

Add an <internet/> kind to requires/recommends/supports (2)

---

docs/xml/metainfo-component.xml
src/as-relation.c
src/as-relation.h
tests/test-xmldata.c
tests/test-yamldata.c

This is a version of https://github.com/ximion/appstream/pull/425 with some minor fixes and added validation.

Add an <internet/> kind to requires/recommends/supports /3

---

tools/ascli-actions-mdata.c

The command `appstreamcli refresh-cache --cachepath /tmp/cache` segfaults. In this code path, `ret` (initialized to `FALSE`) is not updated when `as_pool_load` returns successfully and sets the `error` pointer to NULL. Then the code tries to print `error->message`.

ascli_refresh_cache: fix NULL pointer dereference

---

qt/chelpers.h
qt/pool.cpp

It was crashing because the list was not getting populated properly. This changes does so and addresses a couple of extra problems found while doing this as seen in their respective commits2.

Addresses some problems found while trying to use Pool::componentsByCategories

---

src/as-review.c

See the commit messages for details.
The bulk of the changes here are to correctly emit `GObject::notify` when properties on `AsReview` are changed. The rest of the changes are mostly best practice / cleanup.

Improve GObject property implementation in AsReview

---

src/as-validator-issue-tag.h
src/as-validator.c

I added the following checks:
- At least one Screenshot must be a default
- Width and Height must be Integers
- `source` and `thumbnail` are the only allowed values for a Image type
- If a Image type is  `thumbnail`, it must have 'width' and 'height'
- Only one Image with type `source` per language is allowed for each Screenshot
- If a Screenshot is a Image, it must contain a source Image

Improve Screenshot validation

---

compose/asc-compose.c
compose/asc-hint-tags.c
compose/asc-utils-metainfo.c
compose/asc-utils-metainfo.h
data/its/metainfo.its
data/its/metainfo.loc
docs/xml/collection-xmldata.xml
docs/xml/metainfo-component.xml
docs/xml/releases-data.xml
src/as-component-private.h
src/as-component.c
src/as-component.h
src/as-context-private.h
src/as-context.c
src/as-metadata.c
src/as-metadata.h
src/as-news-convert.c
src/as-validator-issue-tag.h
src/as-validator.c
src/as-validator.h
src/as-xml.c
src/as-xml.h
tests/samples/org.example.pomidaq.metainfo.xml
tests/samples/releases/org.example.pomidaq.releases.xml
tests/test-xmldata.c
tools/ascli-actions-validate.c

Hi!
This PR contains the specification for a "new" metadata format that contains release descriptions. Having them split out of the main metainfo file allows them to be updated independently and separately, and even allows us to fetch updated release information automatically at catalog build time.
This PR follows the discussion at #354 
Short summary of the changes:
* To use external release metadata, the main metainfo component must contain a `releases` tag with the property `external="yes"` (*note: maybe `type="external"` is better / more consistent?*). This is done so we don't need to `stat()` around too much and to have the metadata author communicate their intent clearly (good for validation!).
* External release metadata files follow the existing specification for AppStream …

Specify a metadata format for external release descriptions

---

qt/pool.cpp
qt/pool.h
src/as-cache.c
src/as-cache.h
src/as-pool.c
src/as-pool.h

It's often that we will need to look up packages by their name. Include some API that helps us do it.
WIP because it would be necessary to look up by e.g. `org.kde.dolphin` too, not just `org.kde.dolphin/x86_64/master`. Some idea on how to do this would be useful.
Context for this change is here:
https://invent.kde.org/plasma/discover/-/merge_requests/455

pool: Offer API to look up by bundles

---

src/as-relation.c

Use 'may' instead of 'my' in as-relation.c

---

docs/xml/catalog-iconcache.xml

Rationale: https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/1574#note_1625290

docs: Clarify the locations where catalog icons should be placed

---

docs/xml/releases-data.xml

See the commit messages.
This should hopefully resolve #458, although there may be things I’ve missed or have worded badly.
I also haven’t been able to preview the generated HTML, because I don’t have `daps` installed and from some quick searching around I can’t find it packaged for Fedora. I have run my changes through `xmllint` at least.
Closes #458

spec: Expand documentation for <issue> elements

---

src/as-release.c

Allows to fail with a loud message on what happened before an actual issue.

release: Add sanity checks at beginning of each function

---

compose/meson.build

FreeBSD and MacOS variants of `sed` do not accept `-i` parameter without any argument.

Make sed invocation more portable

---

docs/xml/metainfo-component.xml

The doc says, that the property must be named `id`, but the example uses `type`.
btw:
Is agreement actually used? anywhere?

Fix agreement example

---

qt/pool.cpp
qt/pool.h
src/as-cache.c
src/as-cache.h
src/as-pool.c
src/as-pool.h
tests/test-pool.c

On certain systems a refresh is necessary in such cases and, in any case, it's useful to know whether queries are pointless.
---
I wonder if it would make sense to be more specific about what we are looking up, since I guess it could be getting confused by fwupd or flatpak...

Add API for asking whether the pool is empty

---

src/as-spdx.c
tests/test-basics.c

something like: "CC0-1.0 AND (BSD-3-Clause OR LGPL-2.1-only)" is reported by appstreamcli check-license as "invalid" and not "Free and Open Source"
$ appstreamcli check-license "CC0-1.0 AND (BSD-3-Clause OR LGPL-2.1-only)" License Type: invalid
Suitable for AppStream metadata: no
Free and Open Source: no
Trying to debug I find that "as_license_is_free_license" accepts this string as valid, but that "as_is_spdx_license_expression" considers it invalid due to the presence of "(" and ")" so it is rejected there and so ascli_check_license goes on to use as_license_to_spdx_id which turns it into "CC0-1.0-1.0 AND (BSD-3-Clause-3-Clause OR LGPL-2.1-only)" ascli_check_license is ok with brackets, but at this point its mangled and understandably fails.
In fedora in practice I see gnome-software …

brackets in spdx license expression rejected by as_is_spdx_license_expression

---

qt/meson.build
qt/tests/meson.build

Disables warning checks on include files found in Qt 6 headers.
Fixes building against Qt 6.5.0 on archlinux.

Make Qt6 dependency a system dependency.

---

src/meson.build

Building libadwaita via jhbuild with meson-0.64.0,
meson.build:227:4: ERROR: Problem encountered: Unable to fix up the .pc file:
sed: can't read /home/jhbuild/.cache/jhbuild/build/libadwaita/subprojects/appstream/meson-private/appstream.pc: No such file or directory
The generated file is found at /home/jhbuild/.cache/jhbuild/build/libadwaita/meson-private/appstream.pc
Use the global build root to find this file and fix the build failure.

Fix tweaking of appstream.pc when building as subproject

---

docs/xml/catalog-xmldata.xml
qt/bundle.h
src/as-bundle.c
src/as-bundle.h

This is a preparation for adding AppStream metadata support for linglong packages. Thus 'linglong' can be used as a valid bundle type in its AppStream catalog metadata.
cc @black-desk

bundle: add linglong as a new type of Bundle

---

data/desktop-style-ids.txt
src/as-desktop-env-data.h

Thanks for adding support for screenshot environments!
This adds IDs for macOS and Microsoft Windows.

Add GUI environment IDs for macOS and Microsoft Windows

---

qt/component-box.cpp
qt/component-box.h

* Adds iterators so that we don't need to create a full QList every time that we get a result. We can iterate it little by little and only keep in memory what we need.
* Adds operator+= and erase() so the ComponentBox can be operated on.

qt: Improve ComponentBox

---

.cirrus-ci.yml
tests/test-pool.c

Testing is omitted for the moment because AsMonitor tests fail due to FreeBSD-specific bug in glib: https://gitlab.gnome.org/GNOME/glib/-/issues/576
I might also miss some dependencies, so the commit might need amending after the repository enables Cirrus CI.
Obsoletes https://github.com/ximion/appstream/pull/485 PR

Add FreeBSD CI using Cirrus CI.

---

docs/meson.build

Currently, if the docbook-xsl catalog isn't found, it results in a build error. This PR checks that xsltproc can successfully find the docbook catalogs it needs. This is important, because the `meson setup` step should detect if the dependencies needed are there instead of waiting for a compilation failure.
I was able to get building of the man pages to work in macOS, it requires the following steps:
1. `brew install docbook-xsl`
2. `export XML_CATALOG_FILES=/opt/homebrew/etc/xml/catalog`

Check for DocBook XSL Catalogs

---

src/as-validator-issue-tag.h

I tried to validate https://github.com/LibreSprite/LibreSprite/blob/4dac17fd198288d91c07592373449dcdddaf7e24/desktop/libresprite.appdata.xml and got this error:
```
$ flatpak run org.freedesktop.appstream.cli validate --explain desktop/libresprite.metainfo.xml
E: ~:2: metainfo-ancient
The metainfo file uses an ancient version of the AppStream specification, which can not be
validated. Please migrate it to version 0.6 (or higher).
✘ Validation failed: errors: 1
```
I compared it to a valid metainfo file to see the differences at a glance.
I think adding the explanation regarding the different root tag would be helpful.

Explain metainfo-ancient error in more detail

---

qt/cmake/AppStreamQt5Config.cmake.in

Fixes build of projects against packagekit-qt5. I didn't touch the target name, but you may want to rename it to AppStreamQt5 for consistency.

Fix lib name for Qt5 link target

---

meson.build
src/as-system-info.c

This is probably a follow-up for 02ee2d0daa ("fix macos build") and unbreaks the build on Nixpkgs x86_64-darwin. I don't know why, probably due to using even older SDKs? :upside_down_face: 
https://github.com/NixOS/nixpkgs/runs/19486840382
https://logs.ofborg.org/?key=nixos/nixpkgs.273297&attempt_id=05115a28-17b2-4d53-b0e9-d6c2f6a02b63
```
> In file included from ../src/as-system-info.c:60:
> In file included from /nix/store/51c1k4sj0irwgyvkgbyhqi0ggilyh3j2-Libsystem-1238.60.2/include/sys/sysctl.h:83:
> /nix/store/51c1k4sj0irwgyvkgbyhqi0ggilyh3j2-Libsystem-1238.60.2/include/sys/ucred.h:91:2: error: unknown type name 'u_long'
>         u_long  cr_ref;                 /* reference count */
>         ^
> 1 error generated.
> ninja: build stopped: subcommand failed.
```
Update: Instead of …

meson: Pass -D_DARWIN_C_SOURCE on darwin

---

docs/xml/metainfo-component.xml

Not sure if this is correct, but `appstreamcli validate` doesn't complain about it.

Docs: Mention that <summary/> tag can be translated

---

qt/component.cpp
qt/component.h

Since it was omitted, add the const and overload the method for now.

qt: Component::customValue should be const

---

src/as-system-info.c

According to the [GLib doc](https://docs.gtk.org/glib/func.pattern_match_simple.html) the globbed pattern is the first argument, while the string to test comes after.
This fixes the fact that `as_system_info_has_device_matching_modalias` could return `TRUE` for a 1:1 equality with the pattern, but always returned `FALSE` when using wildcards.

sysinfo: Swap arguments of g_pattern_match_simple

---

docs/xml/metainfo-component.xml

Github very specifically puts all user hosted websites under `github.io` as its a completely different domain than `github.com` which controls all officially hosted websites.
Using `io.github` for an ID makes it explicitly clear it is not associated with an official Github project which certainly could be packaged.

Use io.github for ID example

---

src/as-validator.c

See https://github.com/flathub/flathub/issues/5005 for reference

Validate that lists don't get translated

---

docs/api/appstream.toml.in

Improve discoverability of the AppStreamCompose API in AppStream API docs, in a similar way as it's done between Glib, GIO and GObject in their docs.

docs: List AppStreamCompose as related to AppStream

---

data/desktop-style-ids.txt
src/as-desktop-env-data.h

As discussed in #611 this PR adds Plasma Mobile to the list of desktop style ids.
Let me know if anything is missing

Add Plasma Mobile to desktop-style-ids.txt

---

docs/xml/catalog-xmldata.xml

/usr/share/app-info/(xml|xmls) are no longer scanned

Warn in the documentation that support for the legacy path has been dropped

---

.cirrus.yml

Attempts to resolve Cirrus continuous integration failures observed for recent pull requests / commits.

ci: Attempt to fix build (update `py-gi-docgen`)

---

compose/asc-hint-tags.c
qt/pool.h
src/as-category.c
src/as-content-rating.c
src/as-system-info.c
src/as-utils.c
tests/samples/org.example.pomidaq.metainfo.xml
tests/test-xmldata.c

Refresh & cleanup freedesktop.org web URLs

---

data/desktop-style-ids.txt

Add Pantheon (Dark) to supported list of environment ids

desktop-style-ids: add pantheon:dark

---

qt/release.cpp

Otherwise it loads all the dates as if they were in the local timezone, making it all a bit more complex for no reason.

qt: Specify utc as the dates' timezone

---

tests/test-basics.c
tests/test-misc.c

As of https://github.com/ximion/appstream/pull/510, fetching the Kernel version is not supported on Windows.

Fix some tests on Windows

---

src/as-vercmp.c

This causes rendering issues in web browser.
Refer: https://www.freedesktop.org/software/appstream/docs/api/func.vercmp_simple.html

as-vercmp: Fix gtkdoc to not start with '>'

---

data/desktop-style-ids.txt

Endless OS doesn't make sense as a distinct environment here:
- Our app platform is GNOME/GTK/Adwaita
- Our DE is GNOME Shell (with extensions)
- There's no practical difference between screenshots for Endless OS and screenshots for GNOME
There _are_ some minor default settings differences (Endless OS enables the always-visible-scrollbar accessibility setting and includes minimize/maximize buttons by default), but after discussing with @wjt, we're more comfortable just using the `gnome` IDs here rather than complicating things for a minuscule difference.
We do set the `XDG_CURRENT_DESKTOP` to `Endless:GNOME` on Endless OS, but if I'm understanding things correctly, we should still be able to have GNOME Software just show the GNOME screenshots first. :)

desktop-style-ids: Remove Endless

---

src/as-system-info.c

The [POSIX specifies](https://pubs.opengroup.org/onlinepubs/9799919799/functions/uname.html) that `uname()` returns non-negative value on success.
This PR makes the `uname()` failure checking more POSIX compliant to make it working properly on platforms like illumos or Solaris.

sysinfo: make uname() usage POSIX compliant

---

docs/xml/catalog-xmldata.xml
src/as-bundle.c
src/as-bundle.h

This is needed for GNOME Software to have a correct bundle type for systemd-sysupdate.

bundle: Add AS_BUNDLE_KIND_SYSUPDATE

---

.github/workflows/build-test.yml

This reverts pull request #655, which explicitly updated the Ubuntu runner version for the Debian Testing builds in GitHub Actions to use 24.04 due to a syscall `seccomp.json` policy incompatibility.
~~:warning: Strictly speaking `ubuntu-latest` remains [scheduled](https://github.com/actions/runner-images/issues/10636) to become `ubuntu-24.04` on 2025-01-17, despite that issue tracker task being closed, so to be cautious it may make sense to wait until that date before merging this.~~
Edit: strikethrough the warning note in the description because we are comfortably past the migration date.

Revert "ci: Update to Ubuntu 24.04 for Debian Testing builds"

---

src/as-validator-issue-tag.h

Otherwise, statically-linked builds fail, because this symbol is duplicated into the object file for every .c file that includes it, and they clash:
/nix/store/jdn0xxjrqqppv2j5dmsspiykbal4ypam-x86_64-unknown-linux-musl-binutils-2.43.1/bin/x86_64-unknown-linux-musl-ld: src/libappstream.a(as-validator.c.o):(.data.rel.local+0x0): multiple definition of `as_validator_issue_tag_list'; compose/libappstream-compose.a(asc-globals.c.o):(.data.rel.local+0x0): first defined here

validator: mark as_validator_issue_tag_list static

---

src/as-utils.c

The file has set the attributes after commit c6903ab9db7dc702fdff1e4964fab49a3d0de91c, thus this is not needed.
If it was meant to set the executable flag on the parent directory, then it is not needed either, at least according to my tests. The `path_dest` points to the installed file here, not to the parent directory.
Closes https://github.com/ximion/appstream/issues/681

utils: Remove leftover g_chmod()

---

src/as-metadata.c
src/as-utils.c
src/as-zstd-decompressor.c

There is already the ZSTD compression support built in, but it was not extended into the appstream data installation, which is the place the code will reach it first, because the ZSTD can be used in the repositories.
See the respective commits for the various fixes done along the way.

Various fixes related to Appstream data installation and ZSTD support

---

qt/utils.cpp
qt/utils.h

Expose `as_markup_covert()` function and `AsMarkUpKind` enum, so Qt clients can use the description fields in other suitable formats, such as markdown or simple text

qt: Expose markup conversion utils

---

compose/asc-utils-fonts.c

Previously, compose would generate screenshot thumbnails for fonts in the media directory but not actually insert screenshot tags into the resulting font component.
Resolves #710.

compose: Insert screenshot tags for auto-generated font screenshots

---

compose/asc-utils-fonts.c

compose: Accept .ttc font files

---

data/meson.build
tools/meson.build

Using the target build require an exe-wrapper.

meson: don't override appstreamcli when cross-building

---

compose/asc-font.c

This is to avoid alignment issues when presenting text, e.g. font icons
Before:
After:
Part of #717

compose: Trim substring when truncating font sample text
